name: reusable
on: 
  workflow_call:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
        echo "org variable : ${{ vars.TEST_ORG_VAR }}"
        echo "overriden variable : ${{ vars.OVERRIDE_VAR }}"
