name: run name test lab
on: 
  workflow_dispatch:
  
run-name: Test run-name using ${{ vars.RUN_NAME }}

jobs:
  display-secrets-and-variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
        echo "org variable : ${{ vars.TEST_ORG_VAR }}"
        echo "env variable : ${{ vars.LARGE_ENV_VAR_NAME }}"
        echo "env context variable : ${{ env.TEST_ENV_VAR }}"
        echo "env variable should not print : ${{ vars.SEC_ENV_VAR }}"
        echo "overriden variable : ${{ vars.LARGE_OVERRIDE_VAR }}"
