name: reusable
on: 
  workflow_call:
    inputs:
      username:
        required: false
        type: string
        default: 'dev'

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo ${{ vars[format('{0}_A', vars.foo)] }}
        echo "input var : ${{ inputs.username }}
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
        echo "org variable : ${{ vars.TEST_ORG_VAR }}"
        echo "overriden variable : ${{ vars.OVERRIDE_VAR }}"
