name: variables test
on: 
  workflow_dispatch:
run-name: Test run-name using ${{ vars.RUN_NAME }}

jobs:
  display-secrets-and-variables:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "repo variable : ${{ vars.TEST_REPO_VAR }}"
        echo "org variable : ${{ vars.TEST_ORG_VAR }}"
        echo "overriden variable : ${{ vars.OVERRIDE_VAR }}"
